[project]
name = "ppdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "nicegui>=3.0.4",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
]
